Initial build
fisheyehq/module-hyva-page-builder pull request #1
Opened 2021-03-07 08:46 UTC by johnhughes1984

See README for further detail/context

2021-03-07 13:28 UTC, pykettk commented on Plugin/OverridePageBuilderTemplates.php
> +        if (strpos($result, self::GRID_WIDGET_TEMPLATE) !== false) {
Do we care about case sensitivity here?

2021-03-07 13:36 UTC, pykettk requested changes
Just minor documentation changes from me.

2021-03-07 13:36 UTC, pykettk commented on view/frontend/templates/catalog/product/widget/content/carousel.phtml
> +                <?= $block->getLayout()->getBlock('product_list_item')
```suggestion
                <?= /** @noEscape */ $block->getLayout()->getBlock('product_list_item')
```

2021-03-07 13:36 UTC, pykettk commented on view/frontend/templates/catalog/product/widget/content/carousel.phtml
> +        <?= $block->getBlockHtml('pagebuilder.carousel.nav') ?>
```suggestion
        <?= /** @noEscape */ $block->getBlockHtml('pagebuilder.carousel.nav') ?>
```

2021-03-07 13:36 UTC, pykettk commented on view/frontend/templates/catalog/product/widget/content/grid.phtml
> +                    <?= $block->getLayout()->getBlock('product_list_item')
```suggestion
                    <?= /** @noEscape */ $block->getLayout()->getBlock('product_list_item')
```

2021-03-07 13:36 UTC, pykettk commented on view/frontend/templates/catalog/product/widget/content/grid.phtml
> +            <?= $block->getPagerHtml() ?>
```suggestion
            <?= /** @noEscape */ $block->getPagerHtml() ?>
```

2021-03-07 13:49 UTC, johnhughes1984 commented on Plugin/OverridePageBuilderTemplates.php
> +        if (strpos($result, self::GRID_WIDGET_TEMPLATE) !== false) {
In theory* you could have modules with the same name in different cases, so we should keep the case, but appreciated that scenario will likely never arise and cause its own set of problems! I think my answer would be it probably doesn't matter too much either way.

> *Never tried in practice to confirm if it works

2021-03-07 14:09 UTC, pykettk submitted a review, later dismissed

2021-03-08 10:12 UTC, rich-humphreys submitted a review, later dismissed

2021-03-08 10:43 UTC, amanda107 approved these changes

2021-03-09 09:11 UTC, pykettk submitted a review, later dismissed

2021-03-09 11:49 UTC, rob-aimes approved these changes

2021-03-09 15:18 UTC, amanda107 approved these changes

2021-03-09 18:11 UTC, fredden approved these changes

2021-03-09 18:26 UTC, merged